SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS chat_messages;
DROP TABLE IF EXISTS chat_users;
DROP TABLE IF EXISTS chat;
DROP TABLE IF EXISTS garde_messages;
DROP TABLE IF EXISTS garde;
DROP TABLE IF EXISTS message_photos;
DROP TABLE IF EXISTS catalogue_messages;
DROP TABLE IF EXISTS messages;
DROP TABLE IF EXISTS ticket_photos;
DROP TABLE IF EXISTS ticket_messages;
DROP TABLE IF EXISTS tickets;
DROP TABLE IF EXISTS plant_photos;
DROP TABLE IF EXISTS catalogue_photos;
DROP TABLE IF EXISTS photos;
DROP TABLE IF EXISTS plants;
DROP TABLE IF EXISTS catalogue;
DROP TABLE IF EXISTS user_roles;
DROP TABLE IF EXISTS reactions;
DROP TABLE IF EXISTS reaction_catalogue;
DROP TABLE IF EXISTS reaction_tickets;
DROP TABLE IF EXISTS reaction_messages;
DROP TABLE IF EXISTS roles;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS guardianships;
DROP TABLE IF EXISTS ticket_comments;
DROP TABLE IF EXISTS status;



SET FOREIGN_KEY_CHECKS = 1;