version: '3.8'
services:
  app:
    build: .
    environment:
      DB_HOST: db
      DB_USERNAME: mspr1_user
      DB_PASSWORD: mspr1_password
    depends_on:
      - db
    ports:
      - "9000:9000"

  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mspr1
      MYSQL_USER: mspr1_user
      MYSQL_PASSWORD: mspr1_password
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
